figma.showUI(__html__,{width:430,height:340});
const rgb=hex=>({r:parseInt(hex.slice(1,3),16)/255,g:parseInt(hex.slice(3,5),16)/255,b:parseInt(hex.slice(5,7),16)/255});
const solid=(hex,a=1)=>hex==='none'?[]:[{type:'SOLID',color:rgb(hex),opacity:a}];
function bytes(s){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',clean=s.replace(/=+$/,'');let bits=0,value=0;const out=[];for(const c of clean){const v=alphabet.indexOf(c);if(v<0)continue;value=(value<<6)|v;bits+=6;if(bits>=8){bits-=8;out.push((value>>bits)&255)}}return new Uint8Array(out)}
figma.ui.onmessage=async message=>{if(message.type!=='import')return;let frame;try{
 const scene=message.scene;if(!scene||!Array.isArray(scene.items)||scene.items.length>5000)throw Error('设计数据不完整');
 const fonts=await figma.listAvailableFontsAsync(),cache=new Map(),images=new Map(),substitutions=new Set();
 async function fontFor(i){const cjk=/[\u3400-\u9fff]/.test(i.text),serif=/Georgia/.test(i.fontFamily);const families=cjk?(serif?['SimSun','Songti SC','Noto Serif SC','Noto Serif CJK SC','Source Han Serif SC','Microsoft YaHei','Noto Sans SC']:['Microsoft YaHei','Noto Sans SC','Noto Sans CJK SC','Arial']):(serif?['Georgia','Times New Roman','Noto Serif','Inter']:['Arial','Inter','Roboto']);let chosen;for(const family of families){chosen=fonts.find(f=>f.fontName.family===family&&/^(Regular|Normal|Book|Roman)$/.test(f.fontName.style));if(chosen)break}if(!chosen)chosen=fonts.find(f=>f.fontName.family==='Inter'&&f.fontName.style==='Regular')||fonts[0];if(!chosen)throw Error('找不到可加载字体');if(chosen.fontName.family!==families[0])substitutions.add(families[0]+' → '+chosen.fontName.family);const key=chosen.fontName.family+chosen.fontName.style;if(!cache.has(key)){await figma.loadFontAsync(chosen.fontName);cache.set(key,true)}return chosen.fontName}
 frame=figma.createFrame();frame.name=`余色 AFTERIMAGE / ${scene.width>700?'桌面':'手机'} / Editable`;frame.resize(scene.width,scene.height);frame.fills=solid('#f3f0e8');frame.clipsContent=true;frame.x=figma.viewport.center.x-scene.width/2;frame.y=figma.viewport.center.y-350;
 for(const i of scene.items){let node,parent=frame,ox=0,oy=0;
  if(i.type==='text'){node=figma.createText();node.fontName=await fontFor(i);node.fontSize=i.fontSize;node.characters=i.text;node.textAutoResize='WIDTH_AND_HEIGHT';node.letterSpacing={unit:'PIXELS',value:i.letterSpacing};node.fills=solid(i.fill,i.opacity);node.x=i.x;node.y=i.y-i.fontSize*.86;node.name='文字 / '+i.text.slice(0,35)}
  else if(i.type==='rect'){node=figma.createRectangle();node.resize(Math.max(.01,i.w),Math.max(.01,i.h));node.x=i.x;node.y=i.y;node.cornerRadius=Math.min(i.radius||0,i.w/2,i.h/2);node.fills=solid(i.fill,i.opacity);node.name='矢量 / 色块'}
  else if(i.type==='line'){node=figma.createLine();const dx=i.x2-i.x1,dy=i.y2-i.y1;node.resize(Math.max(.01,Math.hypot(dx,dy)),0);node.rotation=-Math.atan2(dy,dx)*180/Math.PI;node.x=i.x1;node.y=i.y1;node.strokes=solid(i.stroke,i.opacity);node.strokeWeight=i.strokeWidth;node.name='矢量 / 分隔线'}
  else if(i.type==='image'){if(!images.has(i.src))images.set(i.src,figma.createImage(bytes(i.src.split(',')[1])).hash);node=figma.createRectangle();node.resize(i.w,i.h);node.x=i.x;node.y=i.y;node.fills=[{type:'IMAGE',imageHash:images.get(i.src),scaleMode:i.fit==='contain'?'FIT':'FILL'}];node.name='馆藏画作 / 可替换图像';if(i.clips?.length){const clips=i.clips;const x=Math.max(...clips.map(c=>c.x)),y=Math.max(...clips.map(c=>c.y)),right=Math.min(...clips.map(c=>c.x+c.w)),bottom=Math.min(...clips.map(c=>c.y+c.h));const mask=figma.createFrame();mask.name='画作取景 / 裁切框';mask.resize(Math.max(1,right-x),Math.max(1,bottom-y));mask.x=x;mask.y=y;mask.fills=[];mask.clipsContent=true;frame.appendChild(mask);parent=mask;ox=x;oy=y}}
  if(node){const x=node.x,y=node.y;parent.appendChild(node);node.x=x-ox;node.y=y-oy;if(i.rotation){node.rotation=-i.rotation;node.x=i.x;node.y=i.y}if(i.fill==='none')node.fills=[];if(i.type==='rect'&&i.stroke){node.strokes=solid(i.stroke);node.strokeWeight=i.strokeWidth}}
 }
 figma.currentPage.selection=[frame];figma.viewport.scrollAndZoomIntoView([frame]);const report=`导入完成：${scene.items.filter(i=>i.type==='text').length} 个原生文字层。`+(substitutions.size?'\n字体替代：'+[...substitutions].join('；'):'\n使用本机原字体。');figma.ui.postMessage({type:'done',message:report});figma.notify('余色设计稿已导入，文字与矢量均可编辑。');
 }catch(error){if(frame)frame.remove();figma.ui.postMessage({type:'error',message:'导入未完成：'+error.message})}};
