const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..');
(async()=>{const report={date:new Date().toISOString(),checks:[],errors:[]};function ok(name,v){assert(v,name);report.checks.push(name)}
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');new Function(html.match(/<script>([\s\S]*?)<\/script>/)[1]);ok('JavaScript syntax valid',true);
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--allow-file-access-from-files']});
const page=await browser.newPage({viewport:{width:1440,height:1120},deviceScaleFactor:1});page.on('pageerror',e=>report.errors.push(e.message));let external=[];page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url())});await page.goto('file:///'+path.join(root,'index.html').replaceAll('\\','/'));await page.screenshot({path:path.join(root,'preview-desktop.png'),fullPage:true});
ok('Desktop has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('#next').click();await page.waitForTimeout(800);ok('Next button changes scene and label',(await page.locator('#sector-number').innerText())==='02');
await page.locator('.hero').focus();await page.keyboard.press('End');await page.waitForTimeout(800);ok('End key selects final slide',(await page.locator('#sector-number').innerText())==='03');await page.keyboard.press('ArrowRight');await page.waitForTimeout(800);ok('ArrowRight wraps to first slide',(await page.locator('#sector-number').innerText())==='01');
await page.locator('#next').click();await page.waitForTimeout(130);ok('Mask transition is active',await page.locator('.mask').evaluate(e=>getComputedStyle(e).animationName==='maskSweep'));await page.waitForTimeout(700);
await page.mouse.move(1200,320);await page.waitForTimeout(50);ok('Pointer updates layered parallax',await page.locator('.hero').evaluate(e=>e.style.getPropertyValue('--px')!=='0px'&&!!e.style.getPropertyValue('--px')));
await page.locator('.card').nth(2).click();await page.waitForTimeout(800);ok('District card selects corresponding scene',(await page.locator('#sector-number').innerText())==='03');
await page.locator('.open-pass').first().click();ok('Selected route appears in modal',(await page.locator('#pass-route').innerText()).includes('沉没港'));ok('Ticket download hidden before generation',!await page.locator('#download').isVisible());await page.locator('#alias').fill('测试夜航者');await page.locator('#pass-form button').click();ok('Pass created with user alias',(await page.locator('#ticket-alias').innerText())==='测试夜航者');const download=page.waitForEvent('download');await page.locator('#download').click();const dl=await download;ok('Pass downloads as TXT',dl.suggestedFilename()==='AFTERHOURS-pass.txt');await page.keyboard.press('Escape');ok('Escape closes modal',!await page.locator('#pass-dialog').evaluate(e=>e.open));ok('Focus restored to opener',await page.locator('.open-pass').first().evaluate(e=>e===document.activeElement));
await page.locator('#autoplay').click();ok('Autoplay starts',(await page.locator('#autoplay').getAttribute('aria-pressed'))==='true');await page.mouse.move(1439,1100);await page.waitForTimeout(7300);ok('Autoplay advances scene',(await page.locator('#sector-number').innerText())==='01');await page.locator('#autoplay').click();
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#next').click();ok('Reduced motion changes scene immediately',(await page.locator('#sector-number').innerText())==='02');ok('Reduced motion disables animation',await page.locator('.mask').evaluate(e=>getComputedStyle(e).animationName==='none'));await page.locator('#autoplay').click();ok('Reduced motion prevents autoplay',(await page.locator('#autoplay').getAttribute('aria-pressed'))==='false');await page.mouse.move(800,200);ok('Reduced motion removes parallax transform',await page.locator('.scene.active').evaluate(e=>getComputedStyle(e).transform==='none'));
await page.setViewportSize({width:390,height:844});await page.reload();await page.screenshot({path:path.join(root,'preview-mobile.png'),fullPage:true});ok('Mobile 390px has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#next').click();ok('Mobile carousel remains operable',(await page.locator('#sector-number').innerText())==='02');await page.setViewportSize({width:320,height:700});ok('Mobile 320px has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
ok('No external network dependencies',external.length===0);ok('No runtime errors',report.errors.length===0);
const svg=fs.readFileSync(path.join(root,'AFTERHOURS-desktop-editable.svg'),'utf8');ok('SVG contains editable text and vectors, no raster images',svg.includes('<text ')&&svg.includes('<path ')&&!/<image|foreignObject/.test(svg));report.svgTextCount=(svg.match(/<text /g)||[]).length;report.svgVectorCount=(svg.match(/<(path|rect|circle)/g)||[]).length;
await require('sharp')(Buffer.from(svg)).png().toFile(path.join(root,'preview-svg.png'));await browser.close();report.result='PASS';fs.writeFileSync(path.join(root,'QA-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exit(1)});

